version: '3'

# Flask server port configured in simulation/config.py
# docker-compose build --no-cache 
# docker-compose up
# docker-compose down

services:
  simulation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulation_container
    volumes:
      - .:/app
    ports:
      - "8080:8080" 